apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: order
  template:
    metadata:
      labels:
        type: order
    spec:
       containers:
       - name: user-backend
         image: enzo674/order-service
         ports:
         - containerPort: 5002
---

apiVersion: v1
kind: Service
metadata:
  name: order-backend
spec:
  selector:
    type: order
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
