apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: product
  template:
    metadata:
      labels:
        type: product
    spec:
       containers:
       - name: product-backend
         image: enzo674/product-service
         ports:
         - containerPort: 5001
       imagePullSecrets:
       - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: product-backend
spec:
  selector:
    type: product
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
