name: e-commerce 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ecommerce:
    runs-on: ubuntu-latest
    name: e-commerce
    steps:

    - name: checking code
      uses: actions/checkout@v4
      
    - name: node setup
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 16
        cache: 'npm'
        
    - name: python setup
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        
        
    - name: install dependencies
      run: |
       pip install flask
        
    - name: running static analysis
      uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
